Repository ByteBuildersLabs/BabyBeastsv2, pull requests merged in 2025-02, with the labels that each got.

#87 Feat/implement bag page
  client/src/components/Bag/index.tsx
  client/src/components/Bag/main.css
  client/src/index.css
Labels: FrontEnd, Testnet, Core Dev

#70 FEAT: smart contract model player beast
  dojo/src/dojo/player.cairo
  dojo/src/models.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_player.cairo
Labels: Dojo, ODBoost, Maintainer: Rolo

#85 Submit score and reward distribution
  dojo/src/models.cairo
  dojo/src/systems/actions.cairo
Labels: Dojo, ODBoost

#71 Minigames Modal Design UI v1
  client/package.json
  client/pnpm-lock.yaml
  client/src/assets/img/modal-background.jpg
  client/src/components/Cover/index.tsx
  client/src/components/MiniGamesModal/MiniGamesModal.css
  client/src/components/MiniGamesModal/index.tsx
  client/src/components/Tamagotchi/index.tsx
Labels: ODBoost, Maintainer: Juan

#101 [FEAT]: Refactor beast models and add constants
  dojo/src/constants.cairo
  dojo/src/lib.cairo
  dojo/src/models/beast.cairo
  dojo/src/models/beast_stats.cairo
  dojo/src/models/beast_status.cairo
  dojo/src/systems/actions.cairo
Labels: Dojo

#115 [FIX]: Double key not working
  dojo/src/lib.cairo
  dojo/src/models/beast.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_actions.cairo
Labels: bug, Core Dev

#187 [FEAT]: Optimize gas consuptiom
  dojo/src/constants.cairo
  dojo/src/models/beast.cairo
  dojo/src/models/beast_stats.cairo
  dojo/src/models/beast_status.cairo
  dojo/src/models/food.cairo
  dojo/src/models/player.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/test_food.cairo
  dojo/src/tests/test_player.cairo
  dojo/src/tests/test_stats.cairo
  dojo/src/tests/test_status.cairo
  dojo/src/types/beast.cairo
Labels: HackerHouse

#188 Rename babybeast
  dojo/README.md
  dojo/Scarb.lock
  dojo/Scarb.toml
  dojo/assets/cover.png
  dojo/assets/icon.png
  dojo/dojo_dev.toml
  dojo/dojo_release.toml
  dojo/src/models/beast.cairo
  dojo/src/models/beast_status.cairo
  dojo/src/models/player.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/test_food.cairo
  dojo/src/tests/test_player.cairo
  dojo/src/tests/test_random.cairo
  dojo/src/tests/test_stats.cairo
  dojo/src/tests/test_status.cairo
  dojo/src/tests/utils.cairo
Labels: HackerHouse

#189 [FEAT]: Upgrade all game to latest Dojo version
  dojo/Scarb.lock
  dojo/Scarb.toml
  dojo/src/constants.cairo
  dojo/src/lib.cairo
  dojo/src/models/beast.cairo
  dojo/src/models/beast_stats.cairo
  dojo/src/models/beast_status.cairo
  dojo/src/models/player.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/test_food.cairo
  dojo/src/tests/test_player.cairo
  dojo/src/tests/test_stats.cairo
  dojo/src/tests/test_status.cairo
  dojo/src/tests/utils.cairo
  dojo/src/types/beast.cairo
  dojo/src/types/clean_status.cairo
  dojo/src/types/food.cairo
Labels: HackerHouse

#194 Delete beast stats
  dojo/src/lib.cairo
  dojo/src/models/beast_stats.cairo
  dojo/src/models/beast_status.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_actions.cairo
  dojo/src/tests/test_food.cairo
  dojo/src/tests/test_stats.cairo
  dojo/src/tests/utils.cairo
  dojo/src/utils/random.cairo
Labels: HackerHouse

#195 Rename spawn method to spawn beast
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/test_food.cairo
  dojo/src/tests/test_player.cairo
  dojo/src/tests/test_status.cairo
Labels: HackerHouse

#196 remove unused test
  dojo/src/tests/test_random.cairo
Labels: HackerHouse

#200 Use events for age
  dojo/src/events/beast_age.cairo
  dojo/src/lib.cairo
  dojo/src/models/beast.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/utils.cairo
  dojo/src/utils/math.cairo
Labels: HackerHouse

#208 Fix beast model
  dojo/src/events/beast_age.cairo
  dojo/src/lib.cairo
  dojo/src/models/beast.cairo
  dojo/src/store.cairo
  dojo/src/systems/actions.cairo
  dojo/src/tests/test_beast.cairo
  dojo/src/tests/utils.cairo
  dojo/src/utils/math.cairo
Labels: HackerHouse
